SAR-ARD/s1ard

- S1_NRB/dem.py
- S1_NRB/processor.py
This restructures the DEM and WBM preparation functionalities into a new dedicated module `dem`.
The module contains two functions:
- `dem.prepare`: download DEM tiles and convert them into the MGRS tiling scheme
- `dem.mosaic`: scene-specific mosaicking based on the output of `dem_prepare`
The created folder structure stays the same. A larger change is that the tiles are no longer downloaded for the whole bounding box of all scene geometries (which would download a lot of data for larger scene selections). Instead, only tiles covering individual scenes (plus a buffer) are downloaded. This requires repeated access to the DEM storage servers.
> outsourced and restructured DEM preparation functionality

- S1_NRB/config.py
- S1_NRB/metadata/extract.py
- S1_NRB/metadata/mapping.py
- S1_NRB/metadata/stacparser.py
- S1_NRB/metadata/xmlparser.py
- S1_NRB/nrb.py
- S1_NRB/processor.py
- S1_NRB/validation/schemas/product.xsd
- S1_NRB/validation/schemas/source.xsd
- config.ini
This adds capability for creating S1-NRB products from SM acquisition mode and GRD products.  
The following changes have been made:
- general
* adjust to the new pyroSAR naming scheme for Stripmap products from `SM` to `S1..S6` (**new version yet to be published**)
* enable processing without noise removal and noise power images (currently necessary for SM, see [STEP-32688](https://forum.step.esa.int/t/stripmap-slc-error-during-thermal-noise-removal/32688))
- `config.ini`
* new parameter `product` to differentiate SLC and GRD
- source product JSON
* write mean instead of min for attributes `rangeResolution` and `azimuthResolution`
* write median of all sub-swath values for attributes `rangeNumberOfLooks` and `azimuthNumberOfLooks` (they were expected to the be the same but might actually …
> extended acquisition mode support

- S1_NRB/dem.py
- config.ini
This lets a user avoid interactive prompts to provide a username and password for download of DEM tiles by setting environment variables `DEM_USER` and `DEM_PASS`.
> set dem download authentication via env. variables

- S1_NRB/metadata/extract.py
- S1_NRB/metadata/mapping.py
- S1_NRB/metadata/xml.py
- docs/api.rst
- docs/general/geoaccuracy.rst
- docs/general/index.rst
Stage 1 implementation described in https://github.com/SAR-ARD/S1_NRB/issues/33
> Geolocation accuracy

- S1_NRB/dem.py
- environment-dev.yml
- environment.yaml
- setup.py
This fixes some bugs in the handling of DEM nodata handling and properly extrapolates ocean areas where no DEM tiles exist.
| then         | now     |
|--------------|-----------|
| <img width="679" alt="image" src="https://user-images.githubusercontent.com/18419439/177054770-ae617f9b-b7e2-4962-960c-9f231bc99c9c.png"> | <img width="712" alt="image" src="https://user-images.githubusercontent.com/18419439/177054211-5f2170c9-7fd9-4ffa-a01f-44aa9abf5f01.png">     |
> dem handling improvements

- S1_NRB/nrb.py
Hi @johntruckenbrodt , 
thanks for confirming what I already expected after seeing the relevant lines. Could you review my fix for #49?
Cheers, 
Marco
> Fix temporary VRT in `nrb.format` #49

- S1_NRB/nrb.py
- environment-dev.yml
- environment.yaml
- setup.py
A different approach is now used for log scaling in the VRTs. This enables optimal visualization in QGIS and loading the properly scaled array in Python. See function [S1_NRB.nrb.create_vrt](https://s1-nrb.readthedocs.io/en/latest/api.html#S1_NRB.nrb.create_vrt) for details.
```diff
-    <PixelFunctionType>log10</PixelFunctionType>
-    <Scale>10</Scale>
+    <PixelFunctionType>dB</PixelFunctionType>
+    <PixelFunctionArguments fact="10"/>
```
When using the old approach, the images were properly displayed in QGIS, but the `Scale` parameter was ignored in Python.
The used VRT functionality is new in GDAL 3.5.0 and hence this version has also to be used for displaying and reading the images.
> Adjustments to VRT log scaling

- S1_NRB/metadata/stac.py
- S1_NRB/metadata/xml.py
This removes an error source in case the nodata values are adjusted in the future. After the change from `NaN` to `-9999` for the float images, the metadata files contained the wrong value.
> [metadata] read nodata values directly from files (instead of hard-coding them)

- S1_NRB/metadata/stac.py
One aspect that might need to be discussed with this PR is that I changed the asset keys of the main backscatter assets (e.g. from `vh` to `vh-g-lin`). What do you think @johntruckenbrodt ? 
Here is an example of how it currently would look like: 
```json
"vh-g-lin": {
"href": "./measurement/s1a-iw-nrb-20200103t170705-030639-0382d5-32tps-vh-g-lin.tif",
"type": "image/tiff; application=geotiff; profile=cloud-optimized",
"title": "Linear scaled gamma nought backscatter (VH)",
"created": "2022-07-15T16:36:26.569095",
"raster:bands": [
{
"unit": "natural",
"nodata": -9999.0,
"data_type": "float32",
"bits_per_sample": 32
}
],
"file:byte_order": "little-endian",
"file:size": 201582798,
"file:header_size": 6830,
"card4l:border_pixels": 0,
"roles": [
"backscatter",
"data"
]
},
"vv-g-lin": { …
```
> [metadata.stac] add VRT assets

- S1_NRB/metadata/extract.py
- docs/api.rst
I've noticed wrongly calculated footprints due to this issue: https://github.com/opendatacube/odc-stac/issues/83
This should now be fixed as well as another minor bug that I found (error not raised properly). 
The extraction and formatting of geometry information for STAC and XML metadata was completely refactored and the function `convert_coordinates` replaced by `geometry_from_vec`.
> Fix and improve metadata geometry handling

- Dockerfile
- S1_NRB/dem.py
- S1_NRB/processor.py
- environment-dev.yml
- environment.yaml
- setup.py
This bumps up the pyroSAR requirement to >=0.18.0, which is compatible with SNAP 9. This latest SNAP version fixes a bug in stripmap noise power processing, which has now been enabled.
> SNAP 9 compatibility

- S1_NRB/ancillary.py
- S1_NRB/dem.py
- S1_NRB/metadata/extract.py
- S1_NRB/metadata/stac.py
- S1_NRB/metadata/xml.py
- S1_NRB/nrb.py
- S1_NRB/processor.py
- S1_NRB/snap.py
- S1_NRB/tile_extraction.py
This enables buffering of GRD scenes using data from the neighboring scenes. This way, the individual GRDs overlap by some pixels and no gap is introduced after geocoding.
> GRD buffering

- S1_NRB/config.py
- S1_NRB/metadata/extract.py
- S1_NRB/metadata/mapping.py
- S1_NRB/metadata/stac.py
- S1_NRB/nrb.py
- S1_NRB/processor.py
- S1_NRB/snap.py
- config.ini
- docs/api.rst
- docs/general/S1_NRB.rst
- docs/general/folderstructure.rst
- docs/general/usage.rst
- choose between gamma0 RTC ( $\gamma^0_T$ ) and ellipsoidal sigma0 ( $\sigma^0_E$ ) using new configuration parameter `measurement`
- control the annotation layers to add to the product via new configuration parameter `annotation`
- new annotation layer sigma-gamma ratio ( $\gamma^0_T / \sigma^0_E$ ) intended for converting to $\gamma^0_T$ if the base measurement convention is $\sigma^0_E$
> sigma0 processing and annotation layer configuration

- S1_NRB/snap.py
This increases the default value for the SNAP `Terrain-Flattening` parameter `oversamplingMultiple` from 1 to 2 to remove artifacts. The oversampling factor determined by SNAP is not high enough and is now multiplied by 2.
The value can be changed via a new argument `dem_oversampling_multiple` in function [S1_NRB.snap.rtc](https://s1-nrb--78.org.readthedocs.build/en/78/api.html#S1_NRB.snap.rtc).  
Comparsion of scattering area images from processing an EW scene with 40 m pixel spacing and a Copernicus 30 m DEM as input:
| before              | after              |
|----------------------|----------------------|
| ![Screenshot 2023-02-08 104714](https://user-images.githubusercontent.com/18419439/217497579-60c24644-70bd-4966-a3ac-49b3c27b84f1.png)        | ![Screenshot 2023-02-08 …
> SNAP RTC: increase DEM oversampling by a factor of two

- S1_NRB/nrb.py
The SNAP ENVI files (inside the BEAM-DIMAP structure) do not have a nodata metadata value. Therefore, the value 0 was hardcoded in the function `nrb.format`. Now, the nodata value is directly written to the ENVI HDR files during SNAP processing so it can be read by `gdalwarp` when converting the images to their final format. The hardcoded value can thus be removed.
> nrb.format: do not hardcode src_nodata and read it from the data instead

- S1_NRB/ancillary.py
- S1_NRB/cli.py
- S1_NRB/config.py
- S1_NRB/processor.py
- docs/examples/nrb_cube.ipynb
- docs/general/usage.rst
- environment-dev.yml
- environment.yaml
- setup.py
The processor can now be configured via the command line. Full configuration without a config file as well as partial configuration to override only some config file parameters are possible.
In the example, all parameters except `acq_mode` and `annotation` are read from the config file.
```bash
s1_nrb -c config.ini --acq_mode IW --annotation dm,id
```
> enable configuration via command line arguments

- S1_NRB/cli.py
- S1_NRB/config.py
- S1_NRB/processor.py
- config.ini
- docs/general/usage.rst
This extend the functionality of the acquisition time search and filtering:
- parameter `maxdate` in format `%Y-%M-%d` is now interpreted as end of day, e.g. `2021-09-01` -> `2021-09-01 23:59:59.999999`; other formats remain unaffected
- a new parameter `date_strict` can be used for better controlling the time filtering behavior
* strict: start >= mindate & stop <= maxdate
* not strict: stop >= mindate & start <= maxdate
> enhanced time filtering

- S1_NRB/ancillary.py
- S1_NRB/cli.py
- S1_NRB/config.py
- S1_NRB/dem.py
- S1_NRB/metadata/extract.py
- S1_NRB/nrb.py
- S1_NRB/processor.py
- S1_NRB/snap.py
- config.ini
- environment-dev.yml
- environment.yaml
- setup.py
This improves on the general processing workflow stability:
- [dem.mosaic] the progress bar has been removed, which otherwise clutters logfiles in batch jobs
- a new configuration parameter `snap_gpt_args` enables parametrization of the underlying SNAP GPT call; this has been found particularly relevant in an HPC environment where SNAP may try to use more resources than ordered in the SLURM job; all functions of the `S1_NRB.snap` have been extended with an argument `gpt_args` accordingly
- [snap.process](https://s1-nrb.readthedocs.io/en/latest/api.html#S1_NRB.snap.process): a new internal flag `utm_multi` enables processing to a single UTM zone if set to False; this is only intended for debugging and experimentation purposes
- preprocessed GRDs are no longer deleted so that they can be …
> general processor improvements

- S1_NRB/ancillary.py
- S1_NRB/archive.py
- S1_NRB/config.py
- S1_NRB/processor.py
- config.ini
- docs/about/changelog.rst
- environment-dev.yml
- [get_config](https://s1-nrb.readthedocs.io/en/latest/api.html#S1_NRB.config.get_config): strip formatting characters like `\r` from date strings (`mindate`, `maxdate`), which were present when directly passing the arguments via a command line call in bash scripts (12c8e33)
- [group_by_time](https://s1-nrb.readthedocs.io/en/latest/api.html#S1_NRB.ancillary.group_by_time): compute the absolute acquisition time difference to decide whether two scenes go into the same group (a7a149a)
- [processor.main](https://s1-nrb.readthedocs.io/en/latest/api.html#S1_NRB.processor.main): do not reassign variable inside loop (c3d5bf9)
- [processor.main](https://s1-nrb.readthedocs.io/en/latest/api.html#S1_NRB.processor.main): do not raise an error when no scenes were found but just print a message and quit …
> various bug fixes

- S1_NRB/ancillary.py
- S1_NRB/archive.py
- environment-dev.yml
- environment.yaml
- setup.py
This introduces an additional ASF online catalog search to cross-check it with the local catalog in case a scene is suspected to be missing. This was found to be necessary in case a scene from a data take has never been published thus introducing gaps in the data take (see #93).
> datatake gap handling

- S1_NRB/ancillary.py
- S1_NRB/archive.py
This further increases the reliability of STAC search when running the processor in 100s of parallel jobs:
- increased the number of tries for opening/searching the catalog from 3 to 300
- wait 1 second after a failed attempt at opening/searching
> increased STAC access robustness

- S1_NRB/config.py
- S1_NRB/nrb.py
Bug fixes to actually allow the following option:
```
```
> Bug fix to allow `annotation = None`

- S1_NRB/metadata/extract.py
- S1_NRB/nrb.py
This saves the original source metadata in the `source` folder of the processed scene, including the `manifest.safe` and the content of the `annotation` directory.
Currently a subdirectory based on the `productIdentifier` is created to save the files:
Another option would be to use the complete name for the directory. E.g., in this case `S1B_IW_GRDH_1SDV_20211114T190500_20211114T190525_029588_0387F4_527F`. Thoughts @johntruckenbrodt ?
> Save original source metadata 

- S1_NRB/snap.py
... instead of a custom pyroSAR method to be consistent throughout production.
> Use ESA border noise removal

- S1_NRB/nrb.py
It can happen that a geocoded dataset only contains nodata values. Hence, an NRB tile should not be created from it. The function `nrb.get_datasets` now handles a second situation where this might occur and properly discards this dataset from the current NRB production run.
> [nrb] remove dataset if mask is nodata-only

- S1_NRB/config.py
- S1_NRB/nrb.py
- config.ini
- docs/general/usage.rst
- new config parameters in `METADATA`-section:  
- `format` to select between metadata file formats (OGC EO XML and/or STAC JSON)
- `copy_original` to optionally copy the original source metadata
- documentation improvements in _general/usage_
> New metadata config parameters

- S1_NRB/ancillary.py
- S1_NRB/snap.py
- docs/api.rst
In this mode the manifest.safe attributes `sliceNumber` and `totalSlices` are 0, which broke with assumptions in [S1_NRB.ancillary.check_acquisition_completeness](https://s1-nrb.readthedocs.io/en/latest/api.html#S1_NRB.ancillary.check_acquisition_completeness) and resulted in a wrong output in [S1_NRB.snap.grd_buffer](https://s1-nrb.readthedocs.io/en/latest/api.html#S1_NRB.snap.grd_buffer). In `check_acquisition_completeness` an additional cross-check with the ASF database was added. For `grd_buffer` the metadata of the BEAM-DIMAP input file is modified to contain dummy values that work with the SNAP `SliceAssembly` operator (The start time of the datatake and the acquisition duration of the scene are known; dividing one by the other and converting it to integer gives the new slice …
> support for scenes acquired in NRT Slicing mode

- S1_NRB/config.py
- S1_NRB/processor.py
- config.ini
- docs/general/usage.rst
The annotation options `gs` and `sg` depend on which measurement option was chosen (`gamma` or `sigma`). This is easily missed in the config file and users might end up without any of these conversion layers after processing. 
I propose to change this option from:
```ini
```
to: 
```ini
```
> Replace `gs` and `sg` annotation options with `ratio`

- S1_NRB/metadata/extract.py
small fix for the recently introduced copying of original source metadata (https://github.com/SAR-ARD/S1_NRB/pull/104, https://github.com/SAR-ARD/S1_NRB/pull/109).
> [copy_src_meta] fixed bug in reading zip content on Windows

- S1_NRB/metadata/extract.py
- Suppresses numpy warnings as discussed in #125 
- Increase default `block_size` to 30 in order to be evenly divisible by 10980
- Minor improvements
closes #125
> ENL calculation: Suppress warnings and increase default block_size

- docs/general/installation.rst
Requirements change so when installing a specific version, the `environment.yaml` file corresponding to that version should be used.
> [docs] point to right environment.yaml when installing specific version

- S1_NRB/config.py
https://github.com/SAR-ARD/S1_NRB/pull/116 renamed the backscatter ratio IDs `sg` and `gs` to `ratio`. Renaming the defaults applied when the configuration file does not have an `annotation` attribute was missed.
> rename config default annotation IDs gs and sg to ratio

- S1_NRB/snap.py
When processing Stripmap scenes, the list of neighboring scenes can be empty.
> [snap.process] skip GRD buffering if list is empty

- S1_NRB/config.py
- S1_NRB/metadata/extract.py
- S1_NRB/metadata/mapping.py
- S1_NRB/metadata/stac.py
- S1_NRB/nrb.py
- S1_NRB/ocn.py
- S1_NRB/processor.py
- config.ini
- docs/api.rst
- docs/conf.py
- docs/general/usage.rst
This adds a new annotation layer 'wind-modeled backscatter' (suffix wm). Dividing a co-polarization sigma naught measurement in linear scaling by this new layer gives a wind-normalized image (VRT with suffix wn). This new layer does not represent a physical measurement and is intended for visualization only.
---
**NOTE**
This PR depends on recent pyroSAR changes in https://github.com/johntruckenbrodt/pyroSAR/pull/256 and https://github.com/johntruckenbrodt/pyroSAR/pull/257 so a new version needs to be released prior to merging the PR.
---
> wind normalization

- S1_NRB/metadata/stac.py
- S1_NRB/metadata/xml.py
In case the configuration is set to `copy_original = False`, the subdirectories for the original source metadata will not exist and can therefore not be searched for files to add as assets to the top-level metadata files.
> do not look for source metadata files if copying is not user-configured

- S1_NRB/ancillary.py
- S1_NRB/config.py
EW is currently only acquired in GRDM mode with a 40 m spacing and approx. 90 m resolution. This should be relected in the ARD pixel spacing.
> change EW spacing from 20 to 40 m

- S1_NRB/metadata/extract.py
- S1_NRB/metadata/stac.py
- S1_NRB/metadata/xml.py
- S1_NRB/nrb.py
Some minor improvements to align with the Product Specification v1.1:
- Rename `NRApplied` & `NRAlgorithm` to `noiseRemovalApplied` & `noiseRemovalAlgorithm` (d468308ab30bf7851b6092cad2be7b60f0d99b45)
- Move `sampleType` field before `bitValue` (5e9c3eb2cd60e2179db825c2b746f67250fe550d)
...and align (not perfectly, but much better) with the STAC product metadata:
- Improve the order of assets listed in the XML metadata (eccef9a0626fed46d03cd740f245d7cd74604f0e)
> XML product metadata improvements

- S1_NRB/metadata/mapping.py
- S1_NRB/nrb.py
The recently added annotation layer 'wind-modeled backscatter' (#138) will now be correctly formatted using the `COG` driver, with LERC compression (`2e-5` error threshold) and the same nodata value as other float32 GeoTIFF layers (`-9999.0`).
> wind normalization - GDAL options

- S1_NRB/archive.py
This fixes two minor bugs when handling scene paths returned from `STACArchive.select`:
- handling of file URLs with `file://` prefix
- handling of paths with `/./` component
> STACArchive file path handling

- S1_NRB/ancillary.py
- S1_NRB/processor.py
- S1_NRB/snap.py
- S1_NRB/tile_extraction.py
- docs/about/abbreviations.rst
- docs/api.rst
- docs/general/enl.rst
- environment-dev.yml
- environment.yaml
- setup.py
For geocoding, the processor first selects all MGRS tiles in a particular UTM zone with a SAR scene. The bounding box of the selected tiles is then used as subset for geocoding only parts of the scene. It can happen that the selected subset  is too small and SNAP trows an error. This is more likely to occur near the poles where up to nine different UTM zones were observed to overlap with one EW scene.
With this PR, a new function is introduced to buffer the subset geometry to have a minimum overlap of 1% with the scene's footprint to ensure a sufficiently large subset for geocoding.
This is handled by functions `ancillary.buffer_min_overlap`and `tile_extraction.aoi_from_scene`. The latter was outsourced from code in `snap.process`.
> geometry buffering for minimum overlap

- Dockerfile
The `conda/miniconda3` Docker image has not been updated in five years, and it looks like it has finally broken.
(The Debian version it uses was archived by the Debian project recently, and some of the download links now fail.)
Luckily the official Continuum image seems to work as a drop-in replacement.
> Use the official Continuum Docker base image

- S1_NRB/ard.py
The wind-modelled backscatter extracted from the OCN products cannot seamlessly be mosaicked with that of neighouring scenes. A simple gap fill is performed to solve this. Here, the distance for gap filling is increased to make sure no gaps remain.
> increase OCN gap fill distance

- S1_NRB/config.py
Accepted modes are `sar`, `nrb` and `orb`. The `config` module now correctly check for them.
> [config] corrected list of allowed modes

- S1_NRB/metadata/extract.py
Two minor changes: 
- Update link to source product access to `https://dataspace.copernicus.eu`
- Only include link to Geolocation Accuracy reference only if actually computed
> Update metadata links

- S1_NRB/metadata/xml.py
Fixes the following error:
```python
Traceback (most recent call last):
File "bin/s1_nrb", line 33, in <module>
sys.exit(load_entry_point('S1-NRB', 'console_scripts', 's1_nrb')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "click/decorators.py", line 33, in new_func
return f(get_current_context(), *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
> [metadata.xml.product_xml] add geo acc. reference only if performed

- S1_NRB/metadata/extract.py
In the function `extract.calc_wm_ref_stats` a `tempfile.NamedTemporaryFile` is used to create a temporary file name. However, this class does not only return a file name but an open file object. This was causing a permission error on Windows when trying to use the file name in `gdalwarp`. After this change the class is still used but the object is closed before passing the file name to `gdalwarp`. Furthermore, the file now has to be deleted manually, a job that was previously performed automatically by`tempfile.NamedTemporaryFile` upon descoping the opened file object.
> avoid permission error when passing tempfile to gdalwarp

- S1_NRB/search.py
in some situations, the function `search.scene_select` tried to parse a date string when the input was already a `datetime.datetime` object. Furthermore, the function now makes use of `dateutil.parse` to support various date formats.
> [search.scene_select] parse date only if necessary

- S1_NRB/processor.py
Process not running with an SLC. Neighbors should be initiated as a list as when it is called on line 202 in the snap.geocode function; a list is expected ```neighbors=neighbors[i]```
The following error will result processing a SLC:
```
2024-03-13 00:31:05 INFO     Traceback (most recent call last):
File "/opt/conda/envs/nrb_env/bin/s1_nrb", line 8, in <module>
sys.exit(cli())
^^^^^
File "/opt/conda/envs/nrb_env/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/nrb_env/lib/python3.12/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/opt/conda/envs/nrb_env/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
return …
```
> bugfix - adding neighbour to list for SLC processing

- S1_NRB/tile_extraction.py
The function [tile_extraction.aoi_from_scene](https://s1-nrb.readthedocs.io/en/latest/api.html#S1_NRB.tile_extraction.aoi_from_scene) did not differentiate between North and South hemisphere leading to incomplete processing results. With this, the two hemispheres are separated and hence processed separately.
> [aoi_from_scene] fixed bug in handling scenes crossing the equator

- S1_NRB/search.py
- environment-dev.yml
- environment.yaml
- setup.py
This improves the STAC queries in `search.STACArchive` by
- increasing the timeout and enabling users to modify it (new argument `timeout`)
- making use of `pystac-client`'s mechanism for retries instead of the own implementation and enabling users to modify it (new argument `max_retries`)
- significantly increasing the query speed by passing parameters for spatial and temporal querying directly to `pystac_client.client.Client.search` arguments `datetime` and `bbox` instead of to the `filter` argument
> STAC query optimizations

- S1_NRB/processor.py
This fixes errors that occurred while formatting the selection message with the wrong dictionary keys.
> [processor] fixed 'empty selection' message

- S1_NRB/ancillary.py
- S1_NRB/cli.py
- S1_NRB/config.py
- S1_NRB/processor.py
- config.ini
- docs/general/usage.rst
With this, it is possible to process a single scene and skip selection from a database. If the scene is a GRD product, a database query is still performed to select neighboring acquisitions.  
This parameter can only be set when the processing mode is `sar` because ARD generation usually requires more than one scene.
> new configuration parameter 'scene'

- S1_NRB/ancillary.py
- S1_NRB/snap.py
- environment-dev.yml
- environment.yaml
- setup.py
Apply [pyroSAR.ancillary.Lock](https://pyrosar.readthedocs.io/en/latest/api/ancillary.html#pyroSAR.ancillary.Lock) during SAR preprocessing and GRD buffering. This enables processing neighboring GRDs in parallel, which depend on each other for buffering.  
This significantly increases SAR processing scalability using configuration parameter `scene`. However, file locking is not yet applied to all created files and race conditions might still occur.
> use file locking for SNAP processing

- s1ard/metadata/extract.py
This is a preliminary fix until the cause of empty ARD image layers is fixed.  
This is most likely a rare corner case not yet covered in `ard.get_datasets` or the data mask creation process.
> [metadata.extract.calc_enl] raise error when array is empty

- s1ard/metadata/stac.py
...so it can be read as xarray by ogc-stac.
This reverts commit https://github.com/SAR-ARD/s1ard/commit/d66e134d4650c6876ef08a6ae2796259e3b5904d (PR https://github.com/SAR-ARD/s1ard/pull/117).
> use COG media type for VRTs

- s1ard/ancillary.py
- s1ard/ard.py
in order to determine whether an ARD product can be created from a SLC/GRD Level-1 product, an accurate valid data mask of the processed Level-1 product is needed. The footprint in the metadata is only an estimation.  
This data mask used to be created in `s1ard.ard.get_datasets` as part of gathering processing outputs for a certain Level-1 product.  
Now, this functionality has been moved into a dedicated function `s1ard.ancillary.datamask`. Furthermore, the functionality has been made more robust and easy to read.
> valid data mask improvements

- s1ard/ancillary.py
- s1ard/ard.py
- s1ard/dem.py
- s1ard/metadata/extract.py
This stores all temporary files created by `s1ard` in a directory `$TMPDIR/s1ard` and deletes them once they are no longer needed. Before, `$TMPDIR` gradually filled up with files (mostly VRTs) eventually preventing operations like `rm -rf $TMPDIR/*` because of too many items.
> improved tmp file handling

- s1ard/search.py
The function `s1ard.search.check_acquisition_completeness` checks the ASF repository for existing scenes if slice information cannot be retrieved from the metadata (NRT slicing mode). This info is needed for determining whether a scene has neighbors. The case that scenes might be missing on ASF was not considered yet.
> check_acquisition_completeness: catch case when ASF result is empty

- s1ard/metadata/extract.py
This simplifies the code by making use of OGR. Moreover, the code can now handle cases where the footprint edges don't align well, which was causing an error in the old code in some cases.
This is only a preliminary fix until https://github.com/SAR-ARD/s1ard/issues/231 is solved.
> [extract._vec_from_srccoords] code improvements

- s1ard/snap.py
This makes some modifications to the processing workflow so that the products generated during preprocessing are not modified in succeeding steps:
- [snap.nrt_slice_num()](https://s1ard.readthedocs.io/en/latest/api.html#s1ard.snap.nrt_slice_num) is now called in [snap.pre()](https://s1ard.readthedocs.io/en/latest/api.html#s1ard.snap.pre) instead of [snap.grd_buffer()](https://s1ard.readthedocs.io/en/latest/api.html#s1ard.snap.grd_buffer)
- [ancillary.datamask()](https://s1ard.readthedocs.io/en/latest/api.html#s1ard.ancillary.datamask) is now called in [snap.process()](https://s1ard.readthedocs.io/en/latest/api.html#s1ard.snap.process). In [ard.format()](https://s1ard.readthedocs.io/en/latest/api.html#s1ard.ard.format) it is still called but only to retrieve the file name of the previously …
> snap pre modifications

- docs/source/api.rst
- environment-dev.yml
- environment.yaml
- requirements.txt
- s1ard/ancillary.py
- s1ard/search.py
- s1ard/tile_extraction.py
- `ancillary.combine_polygons`
- moved from `search.combine_polygons`
- now also takes a single vector object as input so that its poylgons can be combined into a single multipolygon; In case of a large number of polygons, this may significantly speed up spatial queries (from the MGRS KML file or scene database)
- `search.scene_select`:
- fixed bug in handling of `mindate` and `maxdate` parameters, which prevented search without date constraints
- new argument `cores` for parallelized scene metadata extraction
- `search.STACArchive`/`search.STACParquetArchive`
- allow hex strings for `frameNumber` argument
- simplify filter statement with 'in' operator
- `search.STACParquetArchive`: assume hex strings as value for `s1:datatake` metadata parameter
- `tile_extraction.tile_from_aoi`: …
> scene search optimizations

- s1ard/ard.py
...instead of just checking whether the processor output overlaps with an MGRS tile. This overlap can be so small that no valid pixel is contained in the tiled image products rendering the product useless.  
With this fix, the intersection area must be at least the size of one pixel. Whether single-pixel products are meaningful is still debatable however. See https://github.com/SAR-ARD/s1ard/issues/182.
> require at least one pixel overlap with the MGRS tile

- s1ard/search.py
https://github.com/SAR-ARD/s1ard/pull/254 changed the return value options of `search.asf_select` and `search.ASFArchive.select`. These changes were not applied to `check_acquisition_completeness`.
> search.check_acquisition_completeness bug fix

- s1ard/metadata/extract.py
This is a dummy PR to highlight the changes made in https://github.com/SAR-ARD/s1ard/commit/3fa045cd83c5388acf5ecf81eeb1c41abde10959 (which was accidentally directly pushed to the main branch)..
This fixes a bug where the software threw an error when no external OSV file could be found. A dedicated function `get_osv_info` was written as the result. This function first searches for external OSV files. If none is found, it reads the name of the OSV file used during L1 processing from the manifest.safe metadata file. Either a file name or None (if no file was found) is then written to the NRB product's metadata.
> [metadata.extract] OSV info gathering improvements
