- S1_NRB/__init__.py
- setup.py
This enables pinning the version down to individual commits.
> use setuptools_scm for detailed versioning

- S1_NRB/processor.py
- replaced argument `id_list` (list of pyroSAR ID objects) with `geometries` (list of spatialist Vector objects)
- removed argument `buffer`, which is now hard-coded to 1.5 degrees (to ensure full coverage of overlapping tiles)
- default `epsg=None`, which disables EPSG filtering and creates files for all overlapping MGRS tiles
> prepare_dem interface modification

- S1_NRB/ancillary.py
- S1_NRB/metadata/extract.py
- S1_NRB/metadata/stacparser.py
- S1_NRB/metadata/xmlparser.py
- S1_NRB/processor.py
- docs/S1_NRB.rst
- setup.py
- [metadata] adjustments in `xmlparser._common_procedure_elements`
- [metadata, ancillary] depreciate single-layer data mask
- [metadata] improve parsing of data mask bit values based on GeoTIFF band descriptions
- [processor] call DEM preperation only when `snap_flag=True`
- code formatting
> Various improvements

- S1_NRB/ancillary.py
- S1_NRB/processor.py
This implements a new approach for the color composite VRT file based on the solution presented here:
https://gis.stackexchange.com/questions/423154/gdal-vrt-how-to-create-rgb-composite-from-two-input-geotiff-files-input1-inp
Here is an example of the content of a generated RGB VRT file with the nested approach in band 3:
```xml
<VRTDataset rasterXSize="10980" rasterYSize="10980">
<SRS dataAxisToSRSAxisMapping="1,2">PROJCS["WGS 84 / UTM zone 28N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_merid …
```
> RGB composite

- S1_NRB/etad.py
- S1_NRB/processor.py
This simply adds a new module `etad` with function `process` to make the main script `processor.py` more readable and better separate individual components.
> outsourced ETAD correction to dedicated module

- S1_NRB/nrb.py
This sets the nodata value of all float images to -9999 and additionally fixes some bugs in visualization related to VRT nodata handling.
> adjustments to nodata value

- Dockerfile
- setup.py
minor modifications for smooth installation
> installation update

- S1_NRB/archive.py
- S1_NRB/config.py
- S1_NRB/processor.py
- config.ini
- docs/general/usage.rst
Enables scene search by S1 data take ID. If using STAC for search the catalog items need a custom metadata key `s1:datatake`.
> new configuration parameter 'datatake'

- S1_NRB/metadata/extract.py
Fixes a bug introduced in #104
Closes #107
> Bug fix: Save original source metadata

- S1_NRB/ancillary.py
- S1_NRB/archive.py
- S1_NRB/metadata/extract.py
- S1_NRB/snap.py
- docs/about/abbreviations.rst
- docs/about/index.rst
This adds a table of abbreviations to the documentation in the "about"-section.
> Documentation: Table of abbreviations

- S1_NRB/snap.py
https://s1-nrb.readthedocs.io/en/latest/api.html#S1_NRB.snap.grd_buffer
> fixed bug in GRD buffering of ascending scenes

- environment-dev.yml
- environment.yaml
- setup.py
Dependency was recently added with #103
> Add missing pyproj dependency

- S1_NRB/snap.py
The interpolation is now performed using the slant range time as x coordinate instead of the pixel index. This improves the interpolation:
Furthermore, this now also works with SLCs (fixes https://github.com/SAR-ARD/S1_NRB/issues/130).
> Look direction angle improvements

- docs/general/enl.rst
- docs/general/folderstructure.rst
- docs/references.bib
- update [folder structure](https://s1-nrb.readthedocs.io/en/latest/general/folderstructure.html)
- make use of sphinx bibtex citations (module `sphinxcontrib-bibtex`)
> documentation improvements

- S1_NRB/snap.py
https://github.com/SAR-ARD/S1_NRB/pull/149 should have introduced RTC as default for processing. However, these changes were unfortunately reverted while merging two branches in https://github.com/SAR-ARD/S1_NRB/pull/149/commits/16e661070e202c2dd6cb655f4a1448fb40033140.
> re-introduce recently lost radiometric terrain correction

- S1_NRB/ard.py
- config.ini
- docs/general/usage.rst
Before, all three were combined into one mask band called "water".
> separate ocean, rivers and lakes into separate data mask bands

- S1_NRB/ard.py
- docs/api.rst
fixes https://github.com/SAR-ARD/S1_NRB/issues/162
> use relative paths in wind normalization VRT

- S1_NRB/ard.py
Considered values of the source layover-shadow mask:
- 0: not layover, nor shadow
- 1: layover
- 2: shadow
- 3: layover and shadow (newly added)
Furthermore, the code has been simplified and an error message has been improved.
> layover-shadow mask: handle value 3 (layover and shadow)

- S1_NRB/search.py
defining `vectorobject` via `kwargs` resulted in two conflicting geometries because the function only expected `aoi_tiles` or `aoi_geometry` as geometry arguments.
> [search.scene_select] avoid multiple geometry definitions

- S1_NRB/search.py
When defining a search geometry for [search.scene_select](https://s1-nrb.readthedocs.io/en/latest/api.html#S1_NRB.search.scene_select) via `aoi_geometry` or `vectorobject`, the function returned an incomplete search result. The geometries were directly passed to the underlying search mechanisms and hence only scenes directly overlapping with these geometries were returned. However, the correct result would be all scenes overlapping with all MGRS tiles overlapping with the search geometry.  
Now, the function first collects all MGRS tiles overlapping with the geometry and then passes their bounding box to the search mechanisms. The result is now identical to passing the returned list of MGRS tiles as argument `aoi_tiles` to the function `scene_search` (the third search geometry option).
> [search.scene_select] fixed incomplete result for 'aoi_geometry' and 'vectorobject'

- s1ard/snap.py
> [snap] skip GRD buffering if slice number cannot be determined

- s1ard/ard.py
- s1ard/snap.py
This further ensures that intermediate SNAP processing outputs are exclusively used by the current process.  
Moreover, it is avoided that two processes might try to create the same ARD product at exactly the same time.
> improved file locking during SNAP processing

- s1ard/metadata/extract.py
Contrary to the case in https://github.com/SAR-ARD/s1ard/pull/221, the input array may contain very few valid data points, which are not enough to compute the ENL. In this case no error is thrown and `None` is returned instead.
> [metadata.extract.calc_enl] return None if ENL cannot be computed

- s1ard/search.py
This makes sure that [s1ard.search.collect_neighbors()](https://s1ard.readthedocs.io/en/latest/api.html#s1ard.search.collect_neighbors) returns a maximum of two neighbors. See https://github.com/SAR-ARD/s1ard/issues/233
> [search.collect_neighbors] filter if more than two neighbors are found

- s1ard/metadata/stac.py
.. as addition to https://github.com/SAR-ARD/s1ard/pull/246
> STAC: do not create link fields when URL is None

- environment-dev.yml
- environment.yaml
- requirements.txt
- s1ard/ard.py
The spatialist implementation was occasionally giving a 'TopologyException: side location conflict' error.
> [ard.calc_product_start_stop] use geopandas for intersection

- s1ard/snap.py
> [snap.pre] remove grd border boise for all sentinel-1 satellites
